
services:
  # Development overrides for frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - BFF_HOST=backend:8000
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - NEXT_PUBLIC_BFF_URL=http://backend:8000
      - NEXT_PUBLIC_WS_URL=ws://backend:8000
      - NEXT_PUBLIC_BACKEND_URL=http://backend:5000
      - NEXT_PUBLIC_ENV=development
      - NEXT_PUBLIC_GITHUB_OAUTH_REDIRECT=http://localhost:3000/(auth)/github/callback
    volumes:
      - ./frontend:/app:ro  # Read-only mount for most files
      - ./frontend/src:/app/src:rw  # Read-write for source code
      - ./frontend/app:/app/app:rw  # Read-write for Next.js app directory
      - ./frontend/public:/app/public:rw  # Read-write for public assets
      - frontend-next:/app/.next  # Named volume for .next build cache
      - /app/node_modules  # Anonymous volume for node_modules
    command: npm run dev
    restart: "no"

  # Development overrides for backend (BFF service)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.bff
      target: development
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - .:/app
      - backend-dev-data:/app/data
    command: python -m uvicorn bff.server.main:app --reload --host 0.0.0.0 --port 8000
    restart: "no"

volumes:
  backend-dev-data:
    driver: local
  frontend-next:
    driver: local